name: Test crate

on:
  push:
    paths:
      - src/**/*
      - .github/workflows/test.yml
      - Cargo.lock
      - Cargo.toml
      
  pull_request:

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest

    steps:
      - name: Download code
        uses: actions/checkout@v2

      - name: Setup Cargo cache
        uses: actions/cache@v3
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}

      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: 1.67.0
          override: true
      
      - name: Fetch
        run: cargo fetch --locked
      
      - name: Build
        run: cargo build

      - name: Create env file
        run: touch .env

      - name: Test
        run: cargo test
        env:
          EMAIL: mail@guusvanmeerveld.dev